CREATE TABLE SUPPLIER (
    SUPPLIER_ID NUMERIC(8) PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(25) UNIQUE,
    CONTACT_NAME VARCHAR2(25),
    CITY VARCHAR2(25),
    REGION VARCHAR2(25),
    CONSTRAINT REGION_CHECK CHECK (REGION IN ('N', 'NW', 'NE', 'S', 'SW', 'SE', 'W', 'E'))
);

COMMIT;

