INSERT ALL
	INTO SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,  CONTACT_NAME, CITY, REGION) VALUES (500, 'Maple Supplies', 'John Doe', 'Toronto', 'E')
	INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, CONTACT_NAME, CITY, REGION) VALUES (10000002, 'WestCoast Goods', 'Jane Smith', 'Vancouver', 'W')
	INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, CONTACT_NAME, CITY, REGION) VALUES (10000003, 'Northern Imports', 'Michael Lee', 'Edmonton', 'N')
	INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, CONTACT_NAME, CITY, REGION) VALUES (10000004, 'Sunshine Traders', 'Emily Johnson', 'Miami', 'SE')
	INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, CONTACT_NAME, CITY, REGION) VALUES (10000005, 'Prairie Essentials', 'Robert Brown', 'Winnipeg', 'NW')
SELECT * FROM DUAL;

COMMIT;