CREATE TABLE DEPARTMENT (
    DNO NUMBER(*,0),
    DNAME VARCHAR2(30) NOT NULL,
    DLOCATION VARCHAR2(30) NOT NULL,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DNO),
    CONSTRAINT DEPARTMENT_DNAME_UN UNIQUE (DNAME),
    CONSTRAINT DEPARTMENT_DLOCATION_UN UNIQUE (DLOCATION)
);
CREATE TABLE EMPLOYEE (
    ENO CHAR(4),
    ENAME VARCHAR2(30) NOT NULL,
    JOB VARCHAR2(30) NOT NULL,
    MANAGER CHAR(4),
    JDATE TIMESTAMP NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')) NOT NULL,
    SALARY NUMBER(8,2) CHECK (SALARY > 0) NOT NULL,
    COMMISSION NUMBER(8,2) DEFAULT 0,
    DEPTNO NUMBER(*,0) NOT NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ENO),
    CONSTRAINT EMPLOYEE_DEPTNO_FK FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DNO)
);

-- DROP TABLE DEPARTMENT ;
-- DROP TABLE EMPLOYEE;

-- COMMIT;


INSERT ALL
    INTO DEPARTMENT (DNO, DNAME, DLOCATION) VALUES (1, 'HR', 'Toronto')
    INTO DEPARTMENT (DNO, DNAME, DLOCATION) VALUES (2, 'Finance', 'Vancouver')
    INTO DEPARTMENT (DNO, DNAME, DLOCATION) VALUES (3, 'IT', 'Montreal')
    INTO DEPARTMENT (DNO, DNAME, DLOCATION) VALUES (4, 'Marketing', 'Calgary')
    INTO DEPARTMENT (DNO, DNAME, DLOCATION) VALUES (5, 'Sales', 'Ottawa')
SELECT * FROM DUAL;

-- Inserting 5 records into EMPLOYEE using INSERT ALL
INSERT ALL
    INTO EMPLOYEE (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO) 
    VALUES ('E001', 'Alice Smith', 'HR Manager', NULL, CURRENT_TIMESTAMP, 'F', 75000, 5000, 1)
    
    INTO EMPLOYEE (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO) 
    VALUES ('E002', 'Bob Johnson', 'Accountant', 'E001', CURRENT_TIMESTAMP, 'M', 60000, 2000, 2)

    INTO EMPLOYEE (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO) 
    VALUES ('E003', 'Charlie Brown', 'Software Engineer', 'E002', CURRENT_TIMESTAMP, 'M', 90000, 3000, 3)

    INTO EMPLOYEE (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO) 
    VALUES ('E004', 'Diana Prince', 'Marketing Lead', 'E003', CURRENT_TIMESTAMP, 'F', 85000, 4000, 4)

    INTO EMPLOYEE (ENO, ENAME, JOB, MANAGER, JDATE, GENDER, SALARY, COMMISSION, DEPTNO) 
    VALUES ('E005', 'Edward Stark', 'Sales Executive', 'E004', CURRENT_TIMESTAMP, 'M', 70000, 3500, 5)
SELECT * FROM DUAL;



COMMIT;
