CREATE TABLE DEPARTMENT (
    DNO NUMBER(*,0),
    DNAME VARCHAR2(30) NOT NULL,
    DLOCATION VARCHAR2(30) NOT NULL,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DNO),
    CONSTRAINT DEPARTMENT_DNAME_UN UNIQUE (DNAME),
    CONSTRAINT DEPARTMENT_DLOCATION_UN UNIQUE (DLOCATION)
);
CREATE TABLE EMPLOYEE (
    ENO CHAR(4),
    ENAME VARCHAR2(30) NOT NULL,
    JOB VARCHAR2(30) NOT NULL,
    MANAGER CHAR(4),
    JDATE TIMESTAMP NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')) NOT NULL,
    SALARY NUMBER(8,2) CHECK (SALARY > 0) NOT NULL,
    COMMISSION NUMBER(8,2) DEFAULT 0,
    DEPTNO NUMBER(*,0) NOT NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ENO),
    CONSTRAINT EMPLOYEE_DEPTNO_FK FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT(DNO)
);

DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;
-- Creating the DEPARTMENT table



COMMIT;
