SELECT ORDERITEMS.ORDER#, PRODUCTS.PRODUCT_ID,PRODUCTS.PRODUCT_NAME, ORDERITEMS.QUANTITY
FROM ORDERITEMS
JOIN PRODUCTS ON ORDERITEMS.ISBN = PRODUCTS.PRODUCT_ID
WHERE ORDERITEMS.QUANTITY IS NOT NULL
AND ORDERITEMS.QUANTITY = (
    SELECT MIN (ORDERITEMS.QUANTITY)
    FROM ORDERITEMS
    WHERE ORDERITEMS.ORDER# =
)
