INSERT ALL 
	INTO INSTRUCTOR (ins_id, LASTNAME, FIRSTNAME, CITY, COUNTRY) VALUES (2, 'Anna', 'Raul', 'Toronto', 'CA' )
	INTO INSTRUCTOR (ins_id, LASTNAME, FIRSTNAME, CITY, COUNTRY) VALUES (3, 'Vasudevan', 'Hima', 'Chicago', 'USA' )
SELECT * FROM DUAL;

COMMIT;