INSERT INTO COMM_BRAND (BRAND_ID, BRAND_NAME) VALUES (10004 , 'BirkenStock');
INSERT INTO COMM_BRAND (BRAND_ID, BRAND_NAME) VALUES (10002, 'Uggs');
INSERT INTO COMM_BRAND (BRAND_ID, BRAND_NAME) VALUES (10003, 'Nike');
INSERT INTO COMM_BRAND (BRAND_ID, BRAND_NAME) VALUES (10005, 'New Balance');
INSERT INTO COMM_BRAND (BRAND_ID, BRAND_NAME) VALUES (10006, 'Adidas');