CREATE TABLE COMM_BRAND (
    BRAND_ID INT PRIMARY KEY NOT NULL,
    BRAND_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE COMM_PRODUCT (
    PRODUCT_ID INT PRIMARY KEY NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    BRAND_ID INT NOT NULL,
    PRODUCT_TYPE VARCHAR(255) NOT NULL,
    MATERIAL VARCHAR(255) NOT NULL,
    GENDER VARCHAR(255) NOT NULL,
    FOREIGN KEY (BRAND_ID) REFERENCES COMM_BRAND(BRAND_ID)
);

CREATE TABLE COMM_CART (
    CART_ID INT PRIMARY KEY NOT NULL,
    CART_DATE DATE,
    CART_STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT chk_cart_status CHECK (CART_STATUS IN ('Active', 'Inactive'))
);

CREATE TABLE COMM_CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15), -- Changed from INT(10) to VARCHAR for flexibility
    ADDRESS VARCHAR(255) NOT NULL,
    CART_ID INT NOT NULL,
    FOREIGN KEY (CART_ID) REFERENCES COMM_CART(CART_ID)
);

CREATE TABLE COMM_SHIPPING (
    SHIPPING_ID INT PRIMARY KEY NOT NULL,
    CART_ID INT NOT NULL,
    SHIPPING_ADDRESS VARCHAR(255),
    SHIPPING_STATUS VARCHAR(20) NOT NULL,
    SHIPPING_DATE DATE,
    CONSTRAINT chk_shipping_status CHECK (SHIPPING_STATUS IN ('Pending', 'Shipped', 'Delivered', 'Cancelled')),
    FOREIGN KEY (CART_ID) REFERENCES COMM_CART(CART_ID)
);

CREATE TABLE COMM_PRICE (
    PRODUCT_ID INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    PRODUCT_QUANTITY INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES COMM_PRODUCT(PRODUCT_ID)
);

CREATE TABLE COMM_CART_PRODUCT (
    CART_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (CART_ID, PRODUCT_ID),
    FOREIGN KEY (CART_ID) REFERENCES COMM_CART(CART_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES COMM_PRODUCT(PRODUCT_ID)
);

COMMIT;
